exclude_re = [
    "Cursor<'a>::next",                            # timeout
    "year_width",                                  # timeout
    "Flags::has_change_or_upper_case",             # false positive
    "src/format/mod.rs:96:21: replace << with >>", # false positive
]
