exclude_re = [
    "replace -= with += in SizeLimiter<'a>::pad",          # timeout
    "replace > with == in SizeLimiter<'a>::pad",           # timeout
    "replace -= with /= in SizeLimiter<'a>::pad",          # timeout
    "replace /= with %= in year_width",                    # timeout
    "replace | with ^ in Flags::has_change_or_upper_case", # false positive: or and xor are equivalent here
]
