---
name: Code Coverage
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  generate:
    name: Generate
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Generate coverage
        env:
          LLVM_PROFILE_FILE: "strftime-%m.profraw"
          RUSTFLAGS: "-C instrument-coverage"
          # Unstable feature: https://github.com/rust-lang/rust/issues/56925
          RUSTDOCFLAGS: "-C instrument-coverage -Z unstable-options --persist-doctests target/debug/doctests"
        run: |
          cargo +nightly test --lib
          cargo +nightly test --doc

      - name: Generate HTML report
        run: grcov strftime*.profraw --source-dir . --binary-path target/debug -t html --filter covered -o target/coverage

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::447522982029:role/gha-strftime-ruby-s3-backup-20220817011212567800000002
          role-session-name: GitHubActionsSession@codecov

      - name: Show AWS caller identity
        run: aws sts get-caller-identity

      - name: Upload archives to S3
        run: |
          aws s3 cp --recursive target/coverage/* s3://artichoke-forge-code-coverage-us-west-2/strftime-ruby/ --sse AES256 --exclude '*' --include '*.svg' --content-type 'image/svg+xml'
          aws s3 cp --recursive target/coverage/* s3://artichoke-forge-code-coverage-us-west-2/strftime-ruby/ --sse AES256 --exclude '*' --include '*.html' --content-type 'text/html'
          aws s3 cp --recursive target/coverage/* s3://artichoke-forge-code-coverage-us-west-2/strftime-ruby/ --sse AES256 --exclude '*' --include '*.json' --content-type 'application/json'
          aws s3 cp --recursive target/coverage/* s3://artichoke-forge-code-coverage-us-west-2/strftime-ruby/ --sse AES256 --include '*' --exclude '*.svg' --exclude '*.html' --exclude '*.json'
