---
name: Fuzz
"on":
  schedule:
    - cron: "0 0 * * *"
jobs:
  bytes:
    name: Fuzz bytes
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install nightly Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --no-self-update
          rustup default nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        # run for 30 minutes with a 2GB memory limit and a maximum input length of 2048 bytes
        # the maximum input length is set so that the formatter's size limiter will prevent
        # allocating more memory than the memory limit
        run: cargo fuzz run bytes -- -max_total_time=1800 -rss_limit_mb=2048 -max_len=2048

  string:
    name: Fuzz string
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install nightly Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --no-self-update
          rustup default nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        # run for 30 minutes with a 2GB memory limit and a maximum input length of 2048 bytes
        # the maximum input length is set so that the formatter's size limiter will prevent
        # allocating more memory than the memory limit
        run: cargo fuzz run string -- -max_total_time=1800 -rss_limit_mb=2048 -max_len=2048
