---
name: Fuzz
"on":
  schedule:
    - cron: "0 0 * * *"
jobs:
  bytes:
    name: Fuzz bytes
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.10.0
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run bytes -- -max_total_time=1800 # 30 minutes

  string:
    name: Fuzz string
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.10.0
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run string -- -max_total_time=1800 # 30 minutes
